quarkus.mailer.host=smtp.default.domain
quarkus.mailer.from=defaultuser@default.domain
quarkus.mailer.first.host=smtp.first.domain
quarkus.mailer.first.from=user@first.domain
quarkus.mailer.second.host=smtp.second.domain
quarkus.mailer.second.from=user@second.domain
quarkus.mailer.third.host=smtp.third.domain
quarkus.mailer.third.from==user@third.domain

